apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresImage.serviceName }}
  labels:
    {{- include "microk8s-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresService.type }}
  ports:
    - port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.port }}
      protocol: TCP
      nodePort: {{ .Values.postgresService.nodePort }}
      name: postgres
  selector:
    {{- include "microk8s-postgres.selectorLabels" . | nindent 4 }}
